type TProduct = {
  alt?: string;
  code?: string;
  color?: string[];
  colorType?: string;
  description?: string;
  id?: string;
  image?: string[];
  main_image?: string | StaticImageData;
  price?: number;
  promotion?: number;
  rate?: number[];
  slug?: string;
  stock?: number;
  title?: string;
  url?: string;
  variant?: string;
  categories?: string[];
  tags?: string[];
  details?: string[];
};
